name: PushForge
options:
  bundleIdPrefix: com.pushforge
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "26.2"
settings:
  base:
    SWIFT_VERSION: "5"
    SWIFT_STRICT_CONCURRENCY: targeted
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  PushForge:
    type: application
    platform: macOS
    sources:
      - path: PushForge
        excludes:
          - "Resources/Templates/**"
    resources:
      - path: PushForge/Resources
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pushforge.app
        PRODUCT_NAME: PushForge
        INFOPLIST_FILE: PushForge/Info.plist
        CODE_SIGN_ENTITLEMENTS: PushForge/PushForge.entitlements
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: "NO"
        GENERATE_INFOPLIST_FILE: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    entitlements:
      path: PushForge/PushForge.entitlements
  PushForgeTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: PushForgeTests
    dependencies:
      - target: PushForge
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pushforge.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/PushForge.app/Contents/MacOS/PushForge"
        BUNDLE_LOADER: "$(TEST_HOST)"
